'use strict';

module.exports = {
    ACCESS_TOKEN: 'BQDDNdJSh1htiCNMj5AaiGLTl8_ehrX8Kh9gHWHAYTdap24JpzIk0ONwKYLkgDxemKoUze-V7j1njkPPjoeMsuDFPwSmUrKjzUSjk7_-_7tElc5qA9GDMGmgrc_IbRKCWWraXbx1K0ZreVw-tMpgKPCV0SZTH9Jnfce-nJ_FgWrO7IHRtmZYnzPfqOHnK6N5Sdc3fmjH14TU-uBIHoPtZGtO98mDbvng8gXNVkUqqhULLfvFgYUMcr5_sQUqGVygiLE7MFs_NZ3ZjdjsveElmZgUL9Ri0wVY3CA'
}